# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'aphrodite'
    APP_TYPE: 'app'
    APP_BASE: 'bottle'
    MODULE: 'aphrodite:app'
    CLIENT_ID: 7131
    CLIENT_SECRET: '55df5dde98eb34acb6b0b306a0b200fa'
    DEBUG: true

    QINIU_ACCESS_KEY: 'qe5UGyIEQ8ddfoWQ0RYzM5T5REBMtI674GMVGI5V'
    QINIU_SECRET_KEY: 'h58__Qf06vFUZiSrmdsBKDTPaQLIvTMsOss6t4C8'
    QINIU_BUCKET_NAME: 'wishstone'

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
